// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTvs-Cp294hfsk6B4vL_EVfQ-kZgbryyA',
    appId: '1:556877909874:android:0b7efe0eeea88f5073d7eb',
    messagingSenderId: '556877909874',
    projectId: 'haflaway-f14aa',
    storageBucket: 'haflaway-f14aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7B1SlPbpOpHmYHvnPhHzi85jjO7DGRCE',
    appId: '1:556877909874:ios:9a38fb1f960702e473d7eb',
    messagingSenderId: '556877909874',
    projectId: 'haflaway-f14aa',
    storageBucket: 'haflaway-f14aa.firebasestorage.app',
    iosBundleId: 'com.haflaway.adminapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOUx0L5nWrBb6-mld6g0SLm7-BgelxyKY',
    appId: '1:556877909874:web:be367633d966bddb73d7eb',
    messagingSenderId: '556877909874',
    projectId: 'haflaway-f14aa',
    authDomain: 'haflaway-f14aa.firebaseapp.com',
    storageBucket: 'haflaway-f14aa.firebasestorage.app',
    measurementId: 'G-T25SRX978W',
  );

}